### ISSUE TITLE
Mocks missing arguments

### ISSUE THREAD

**Issue by sgp667** [dchelimsky/rspec#71]
I am using Ubuntu 14.04, ruby 2.1, rspec 3.2.3

Whenever I try to run a test I get following Argument error:

     Failure/Error: Unable to find matching line from backtrace
     ArgumentError:
       wrong number of arguments (0 for 1)
     # /usr/lib/ruby/vendor_ruby/rspec/mocks.rb:10:in `setup'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/mocking_adapters/rspec.rb:19:in `setup_mocks_for_rspec'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:378:in `run_before_example'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:176:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:385:in `block in with_around_and_singleton_context_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:343:in `block in with_around_example_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:474:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:612:in `run_around_example_hooks_for'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:474:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:343:in `with_around_example_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:385:in `with_around_and_singleton_context_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example.rb:174:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:549:in `block in run_examples'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:545:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:545:in `run_examples'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:512:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:513:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:110:in `block (3 levels) in run_specs'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:110:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:110:in `block (2 levels) in run_specs'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1526:in `with_suite_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:109:in `block in run_specs'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/reporter.rb:62:in `report'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:108:in `run_specs'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:86:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
     # /usr/local/bin/rspec:23:in `load'
     # /usr/local/bin/rspec:23:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

What is very interesting to me is that I haven't even managed to finish writing my test yet alone incorporate a Mock.

When I looked at the source code of the files mentined in stacktrace I noticed that :

     # /usr/lib/ruby/vendor_ruby/rspec/mocks.rb:10:in `setup'

- is demanding `host` parameter

     # /var/lib/gems/2.1.0/gems/rspec-core-3.2.3/lib/rspec/core/mocking_adapters/rspec.rb:19:in `setup_mocks_for_rspec'

- is not supplying any arguments at all
- instead here is the line 
19           ::RSpec::Mocks.setup 

I am still very new to ruby so I apologize if I missed something obvious.

**Comment by dchelimsky** [comment]
Sorry - I never updated this repo to reflect this but this is not where rspec is maintained any longer. This issue should be reported to https://github.com/rspec/rspec-core or https://github.com/rspec/rspec-mocks.

Good luck!
